/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type DidYouKnowCard = {
  icon?:
    | 'home'
    | 'racquet'
    | 'health'
    | 'money'
    | 'tree'
    | 'community'
    | 'child'
    | 'computer'
    | 'connector'
    | 'art'
    | 'steps'
    | 'traffic-light'
    | 'barrier'
    | 'investment'
    | 'food'
    | 'accessibility'
    | 'calculator'
    | 'bed'
    | 'checkmark'
    | 'gap'
    | 'question-mark'
    | 'tennis-racquet'
    | 'tennis-ball'
    | 'cash'
  eyebrow?: string
  title?: string
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'blockquote'
          | 'largeStatement'
          | 'calloutBox'
          | 'sectionLabel'
        listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
        markDefs?: Array<{
          href?: string
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown // Unable to locate the referenced type "body.image.media" in schema
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
}

export type ContentRowImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "contentRow.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type ColumnImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "column.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type InteractiveSitePlanBlock = {
  _type: 'interactiveSitePlanBlock'
  sectionId?: string
  background?: 'white' | 'cream' | 'mist'
  title?: string
  sitePlanImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  hotspots?: Array<{
    number: number
    positionX: number
    positionY: number
    label: string
    description?: string
    _type: 'hotspot'
    _key: string
  }>
}

export type ContactCtaBlock = {
  _type: 'contactCtaBlock'
  sectionId?: string
  heading?: string
  subtext?: string
  contactEmail: string
  buttonLabel?: string
  background?: 'navy' | 'forest' | 'image'
  backgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type FullWidthImageBlock = {
  _type: 'fullWidthImageBlock'
  sectionId?: string
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type FaqBlock = {
  _type: 'faqBlock'
  sectionId?: string
  background?: 'white' | 'cream' | 'mist' | 'navy' | 'forest'
  title?: string
  items?: Array<{
    question: string
    answer?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?:
            | 'normal'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'blockquote'
            | 'largeStatement'
            | 'calloutBox'
            | 'sectionLabel'
          listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
          markDefs?: Array<{
            href?: string
            openInNewTab?: boolean
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt: string
          caption?: string
          _type: 'image'
          _key: string
        }
    >
    _type: 'faqItem'
    _key: string
  }>
}

export type AboutThreeColumnBlock = {
  _type: 'aboutThreeColumnBlock'
  sectionId?: string
  sectionLabel?: string
  title?: string
  showDivider?: boolean
  introBody?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'blockquote'
          | 'largeStatement'
          | 'calloutBox'
          | 'sectionLabel'
        listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
        markDefs?: Array<{
          href?: string
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
  columns?: Array<{
    image?: ColumnImage
    heading?: string
    body?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?:
            | 'normal'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'blockquote'
            | 'largeStatement'
            | 'calloutBox'
            | 'sectionLabel'
          listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
          markDefs?: Array<{
            href?: string
            openInNewTab?: boolean
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt: string
          caption?: string
          _type: 'image'
          _key: string
        }
    >
    _type: 'column'
    _key: string
  }>
}

export type RezoningBlock = {
  _type: 'rezoningBlock'
  sectionId?: string
  background?: 'white' | 'cream' | 'mist' | 'navy' | 'forest'
  imagePosition?: 'left' | 'right'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  sectionLabel?: string
  title?: string
  showDivider?: boolean
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'blockquote'
          | 'largeStatement'
          | 'calloutBox'
          | 'sectionLabel'
        listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
        markDefs?: Array<{
          href?: string
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
  buttons?: Array<
    {
      _key: string
    } & Button
  >
}

export type SitePlanBlock = {
  _type: 'sitePlanBlock'
  sectionId?: string
  sitePlanImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  legendItems?: Array<{
    number?: number
    label?: string
    _type: 'legendItem'
    _key: string
  }>
  plazaTitle?: string
  plazaImages?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
  plazaCallouts?: Array<{
    heading?: string
    body?: string
    _type: 'plazaCallout'
    _key: string
  }>
}

export type DevStatsBlock = {
  _type: 'devStatsBlock'
  sectionId?: string
  background?: 'white' | 'cream' | 'mist' | 'navy' | 'forest'
  title?: string
  stats?: Array<{
    number: string
    label?: string
    _type: 'stat'
    _key: string
  }>
}

export type AlternatingContentBlock = {
  _type: 'alternatingContentBlock'
  sectionId?: string
  background?: 'white' | 'cream' | 'mist' | 'navy' | 'forest'
  sectionLabel?: string
  title?: string
  intro?: string
  rows?: Array<{
    imagePosition?: 'left' | 'right'
    textBackground?: 'white' | 'cream' | 'mist'
    image?: ContentRowImage
    rowLabel?: string
    rowTitle?: string
    showDivider?: boolean
    body?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?:
            | 'normal'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'blockquote'
            | 'largeStatement'
            | 'calloutBox'
            | 'sectionLabel'
          listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
          markDefs?: Array<{
            href?: string
            openInNewTab?: boolean
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt: string
          caption?: string
          _type: 'image'
          _key: string
        }
    >
    inlineNote?: string
    _type: 'contentRow'
    _key: string
  }>
}

export type CommunityBenefitBlock = {
  _type: 'communityBenefitBlock'
  sectionId?: string
  sectionLabel?: string
  title?: string
  introBody?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'blockquote'
          | 'largeStatement'
          | 'calloutBox'
          | 'sectionLabel'
        listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
        markDefs?: Array<{
          href?: string
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
  totalNumber?: string
  totalLabel?: string
  totalSub?: string
  cacSummaryItems?: Array<string>
  addedBenefitItems?: Array<string>
  accordionItems?: Array<{
    label: string
    itemType?: 'cac' | 'addedBenefit'
    body?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?:
            | 'normal'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'blockquote'
            | 'largeStatement'
            | 'calloutBox'
            | 'sectionLabel'
          listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
          markDefs?: Array<{
            href?: string
            openInNewTab?: boolean
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt: string
          caption?: string
          _type: 'image'
          _key: string
        }
    >
    _type: 'benefitItem'
    _key: string
  }>
}

export type CacCalculationBlock = {
  _type: 'cacCalculationBlock'
  sectionId?: string
  badgeText?: string
  sectionLabel?: string
  title?: string
  showDivider?: boolean
  introBody?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'blockquote'
          | 'largeStatement'
          | 'calloutBox'
          | 'sectionLabel'
        listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
        markDefs?: Array<{
          href?: string
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
  introImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  imagePosition?: 'left' | 'right'
  stepsTitle?: string
  steps?: Array<{
    stepLabel: string
    body?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?:
            | 'normal'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'blockquote'
            | 'largeStatement'
            | 'calloutBox'
            | 'sectionLabel'
          listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
          markDefs?: Array<{
            href?: string
            openInNewTab?: boolean
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt: string
          caption?: string
          _type: 'image'
          _key: string
        }
    >
    _type: 'step'
    _key: string
  }>
  formulaResidentialLabel?: string
  formulaResidentialSub?: string
  formulaHotelLabel?: string
  formulaHotelSub?: string
  formulaResultLabel?: string
}

export type EconomicImpactBlock = {
  _type: 'economicImpactBlock'
  sectionId?: string
  backgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  sectionLabel?: string
  headline?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'blockquote'
          | 'largeStatement'
          | 'calloutBox'
          | 'sectionLabel'
        listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
        markDefs?: Array<{
          href?: string
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
  stats?: Array<{
    number: string
    label?: string
    description?: string
    _type: 'stat'
    _key: string
  }>
  tableTitle?: string
  tableRows?: Array<{
    label?: string
    value?: string
    jobs?: string
    isTotalRow?: boolean
    _type: 'tableRow'
    _key: string
  }>
  footnote?: string
}

export type ProcessBlock = {
  _type: 'processBlock'
  sectionId?: string
  background?: 'white' | 'cream' | 'mist' | 'navy' | 'forest'
  imagePosition?: 'left' | 'right'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  sectionLabel?: string
  title?: string
  intro?: string
  accordionItems?: Array<{
    heading: string
    body?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?:
            | 'normal'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'blockquote'
            | 'largeStatement'
            | 'calloutBox'
            | 'sectionLabel'
          listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
          markDefs?: Array<{
            href?: string
            openInNewTab?: boolean
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt: string
          caption?: string
          _type: 'image'
          _key: string
        }
    >
    _type: 'accordionItem'
    _key: string
  }>
}

export type DidYouKnowBlock = {
  _type: 'didYouKnowBlock'
  sectionId?: string
  layout?: 'single' | 'twoColumn'
  background?: 'white' | 'cream' | 'mist' | 'navy' | 'forest'
  icon?:
    | 'home'
    | 'racquet'
    | 'health'
    | 'money'
    | 'tree'
    | 'community'
    | 'child'
    | 'computer'
    | 'connector'
    | 'art'
    | 'steps'
    | 'traffic-light'
    | 'barrier'
    | 'investment'
    | 'food'
    | 'accessibility'
    | 'calculator'
    | 'bed'
    | 'checkmark'
    | 'gap'
    | 'question-mark'
    | 'tennis-racquet'
    | 'tennis-ball'
    | 'cash'
  eyebrow?: string
  title: string
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'blockquote'
          | 'largeStatement'
          | 'calloutBox'
          | 'sectionLabel'
        listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
        markDefs?: Array<{
          href?: string
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
  rightIcon?:
    | 'home'
    | 'racquet'
    | 'health'
    | 'money'
    | 'tree'
    | 'community'
    | 'child'
    | 'computer'
    | 'connector'
    | 'art'
    | 'steps'
    | 'traffic-light'
    | 'barrier'
    | 'investment'
    | 'food'
    | 'accessibility'
    | 'calculator'
    | 'bed'
    | 'checkmark'
    | 'gap'
    | 'question-mark'
    | 'tennis-racquet'
    | 'tennis-ball'
    | 'cash'
  rightEyebrow?: string
  rightTitle?: string
  rightBody?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'blockquote'
          | 'largeStatement'
          | 'calloutBox'
          | 'sectionLabel'
        listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
        markDefs?: Array<{
          href?: string
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
}

export type TwoColumnTextBlock = {
  _type: 'twoColumnTextBlock'
  sectionId?: string
  background?: 'white' | 'cream' | 'mist' | 'navy' | 'forest'
  sectionLabel?: string
  title?: string
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'blockquote'
          | 'largeStatement'
          | 'calloutBox'
          | 'sectionLabel'
        listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
        markDefs?: Array<{
          href?: string
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
  cardTitle?: string
  cardBody?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'blockquote'
          | 'largeStatement'
          | 'calloutBox'
          | 'sectionLabel'
        listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
        markDefs?: Array<{
          href?: string
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
}

export type ImageTextBlock = {
  _type: 'imageTextBlock'
  sectionId?: string
  imagePosition?: 'left' | 'right'
  background?: 'white' | 'cream' | 'mist' | 'navy' | 'forest'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  sectionLabel?: string
  title: string
  showDivider?: boolean
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'blockquote'
          | 'largeStatement'
          | 'calloutBox'
          | 'sectionLabel'
        listItem?: 'bullet' | 'number' | 'arrowList' | 'dashList'
        markDefs?: Array<{
          href?: string
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
  buttons?: Array<
    {
      _key: string
    } & Button
  >
  didYouKnowCard?: DidYouKnowCard
}

export type HeroBlock = {
  _type: 'heroBlock'
  sectionId?: string
  backgroundImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  eyebrow?: string
  title: string
  body?: string
  buttons?: Array<
    {
      _key: string
    } & Button
  >
  overlayStrength?: 'light' | 'medium' | 'strong'
}

export type Button = {
  _type: 'button'
  label: string
  href?: string
  variant?: 'primary' | 'forest' | 'outlineWhite' | 'outlineDark'
  openInNewTab?: boolean
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'anchor' | 'page'
  href?: string
  anchor?: string
  page?: PageReference
  openInNewTab?: boolean
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  navigation?: Array<{
    label: string
    sectionId: string
    _type: 'navItem'
    _key: string
  }>
  pageBuilder?: Array<
    | ({
        _key: string
      } & HeroBlock)
    | ({
        _key: string
      } & ImageTextBlock)
    | ({
        _key: string
      } & TwoColumnTextBlock)
    | ({
        _key: string
      } & DidYouKnowBlock)
    | ({
        _key: string
      } & ProcessBlock)
    | ({
        _key: string
      } & EconomicImpactBlock)
    | ({
        _key: string
      } & CacCalculationBlock)
    | ({
        _key: string
      } & CommunityBenefitBlock)
    | ({
        _key: string
      } & AlternatingContentBlock)
    | ({
        _key: string
      } & DevStatsBlock)
    | ({
        _key: string
      } & SitePlanBlock)
    | ({
        _key: string
      } & InteractiveSitePlanBlock)
    | ({
        _key: string
      } & RezoningBlock)
    | ({
        _key: string
      } & AboutThreeColumnBlock)
    | ({
        _key: string
      } & FaqBlock)
    | ({
        _key: string
      } & FullWidthImageBlock)
    | ({
        _key: string
      } & ContactCtaBlock)
  >
  seoTitle?: string
  seoDescription?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: string
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  privacyPolicyUrl?: string
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | DidYouKnowCard
  | ContentRowImage
  | ColumnImage
  | InteractiveSitePlanBlock
  | ContactCtaBlock
  | FullWidthImageBlock
  | FaqBlock
  | AboutThreeColumnBlock
  | RezoningBlock
  | SitePlanBlock
  | DevStatsBlock
  | AlternatingContentBlock
  | CommunityBenefitBlock
  | CacCalculationBlock
  | EconomicImpactBlock
  | ProcessBlock
  | DidYouKnowBlock
  | TwoColumnTextBlock
  | ImageTextBlock
  | HeroBlock
  | Button
  | PageReference
  | Link
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Settings
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
